name: NuGet Release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Publish  
        uses: brandedoutcast/publish-nuget@v2.5.2  
        with:   
          PROJECT_FILE_PATH: ./src/GSoft.CertificateTool.csproj
          VERSION_STATIC: ${{ github.event.release.tag_name }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
